- id: misspell
  name: misspell
  description: "Misspell: Correct commonly misspelled English words in source files"
  entry: misspell
  language: golang
  minimum_pre_commit_version: 2.17.0
  types_or: [text]
